# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy necessary files
COPY . .

# Install dependencies (ak sú potrebné)
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt || echo "No dependencies specified"

# Default command
ENTRYPOINT ["python", "main.py"]
