version: '3.8'

services:
  drta-client:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: DRTA-Client
    stdin_open: true  # Enable standard input
    tty: true         # Enable TTY
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true