services:
  drta-client:
    build:
    container_name: DRTA-Client
    volumes:
      - .:/app  # Map the entire directory to the container
    working_dir: /app
    stdin_open: true  # Enable standard input
    tty: true         # Enable TTY
    restart: unless-stopped
