services:
  drta-client:
    build:
      context: .  # Cesta k priečinku s Dockerfile
    container_name: DRTA-Client
    volumes:
      - .:/app  # Mapovanie celého priečinka do kontajnera
    working_dir: /app
    stdin_open: true  # Povoliť štandardný vstup
    tty: true         # Povoliť TTY
    command: ["python", "main.py"]  # Spustiť formulár
    restart: unless-stopped
