FROM python:3.11-alpine

# Nastavenie pracovného adresára
WORKDIR /app

# Install necessary system dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev
RUN pip install --upgrade pip

# Inštalácia závislostí
COPY requirements.txt .
RUN pip install --no-cache-dir -v -r requirements.txt --root-user-action=ignore

# Kopírovanie aplikácie
COPY server.py .

# Run the application
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "key.pem", "--ssl-certfile", "cert.pem"]
