FROM python:3.11-alpine

# Nastavenie pracovného adresára
WORKDIR /app

#Kopírovanie súborov do adresára
COPY . .  
 
# Install necessary system dependencies
# Install build tools and SQLCipher
RUN apk add --no-cache \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    sqlcipher \
    sqlcipher-dev \
    py3-pip

# Inštalácia závislostí
RUN pip install --no-cache-dir -r requirements.txt


# Run the application
#--https --openssl
ENTRYPOINT ["python", "server.py", "--https"] 

