name: Build and Run TOTP Server with Docker Compose

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kódu z repozitára
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Nastavenie environmentálneho súboru
      - name: Setup .env file
        run: |
          echo "TOTP_SECRET=${{ secrets.TOTP_SECRET }}" > server/.env

